port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
tcp-concurrent: true
external-controller: :9090
external-ui: ./ui
geodata-mode: true
global-client-fingerprint: chrome
profile:
  store-selected: true
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  force-domain:
    - "+.netflix.com"
    - "+.nflxvideo.net"
    - "+.amazonaws.com"
    - "+.media.dssott.com"
  skip-domain:
    - "+.apple.com"
    - Mijia Cloud
    - dlg.io.mi.com
  sniff:
    TLS:
    HTTP:
      ports:
        - 80
        - 8080-8880
      override-destination: true
tun:
  enable: false
  stack: mixed
  dns-hijack:
    - "any:53"
  auto-route: true
  auto-detect-interface: true
dns:
  enable: false
  listen: :1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
    - "[2402:4e00::]"
    - "[2400:3200::1]"
  nameserver:
    - "tls://8.8.4.4#dns"
    - "tls://1.0.0.1#dns"
    - "tls://[2001:4860:4860::8844]#dns"
    - "tls://[2606:4700:4700::1001]#dns"
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  nameserver-policy:
    "geosite:cn,private":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
pvd-info: &pvd-info # 更新订阅周期 3天
  interval: 259200
  health-check:
    enable: true
    url: http://www.gstatic.com/generate_204
    interval: 600

all-groups: &all-groups
  proxies:
    [
      🚀 手动切换,
      ♻️ 自动选择,
      🇭🇰 香港节点,
      🇸🇬 新加坡节点,
      🇺🇲 美国节点,
      🇯🇵 日本节点,
      🇰🇷 韩国节点,
      💦 BPB,
      🔞 自建节点,
      DIRECT,
    ]

# 定义自动测速节点
auto: &auto
  type: url-test
  lazy: true
  url: http://www.gstatic.com/generate_204
  interval: 600

all-proxy: &all-proxy
  type: select
  <<: *all-groups

proxy-providers:
  Subscribe:
    type: http
    <<: *pvd-info
    url: "<URL>"
    path: ./Providers/Proxies/Subscribe.yaml

proxy-groups:
  - name: 🚀 手动切换
    type: select
    use:
      - Subscribe

  - name: ♻️ 自动选择
    <<: *auto
    proxies:
      [
        🚀 手动切换,
        🇭🇰 香港节点,
        🇸🇬 新加坡节点,
        🇺🇲 美国节点,
        🇯🇵 日本节点,
        🇰🇷 韩国节点,
        💦 BPB,
        🔞 自建节点,
        DIRECT,
      ]

  - name: 🌍 国外媒体
    type: select
    proxies: [🚀 手动切换, 🇺🇲 美国节点, 🇯🇵 日本节点, 💦 BPB, 🔞 自建节点]
    
  - name: ☁️ 谷歌服务
    type: select
    proxies: [🚀 手动切换, 🇺🇲 美国节点, 🇯🇵 日本节点, 💦 BPB, 🔞 自建节点]

  - name: 🍎 苹果服务
     type: select
    proxies: [DIRECT, 🇭🇰 香港节点, 🇹🇼 台湾节点]
    
  - name: 📺 哔哩哔哩
    type: select
    proxies: [DIRECT, 🇭🇰 香港节点, 🇹🇼 台湾节点]

  - name: 🤖 OpenAi
    type: select
    proxies: [🚀 手动切换, 🇺🇲 美国节点, 🇯🇵 日本节点, 🔞 自建节点]

  - name: 🔞 自建节点
    type: select
    include-all-providers: true
    filter: "sing-box|Oracle|Raksmart|hy2"

  - name: 💦 BPB
    type: select
    include-all-providers: true
    filter: "BPB|💦"

  - name: 🐟 漏网之鱼
    <<: *all-proxy

  - name: 🇭🇰 香港节点
    <<: *auto
    include-all-providers: true
    filter: "🇭🇰|港|HK|hk|Hong Kong|HongKong|hongkong|HKG"

  - name: 🇹🇼 台湾节点
    <<: *auto
    include-all-providers: true
    filter: "🇹🇼|台湾|台北|TW|🇹🇼|Taiwan"

  - name: 🇯🇵 日本节点
    <<: *auto
    include-all-providers: true
    filter: "🇯🇵|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan"

  - name: 🇸🇬 新加坡节点
    <<: *auto
    include-all-providers: true
    filter: "新加坡|🇸🇬|SG|Singapore"

  - name: 🇰🇷 韩国节点
    <<: *auto
    include-all-providers: true
    filter: "韩国|韩|KR|🇰🇷|Korea"

  - name: 🇺🇲 美国节点
    <<: *auto
    include-all-providers: true
    filter: "美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|ATL|BUF|DFW|EWR|IAD|LAX|MCI|MIA|ORD|PHX|PDX|SEA|SJC"

# 定义规则集参数锚点 interval 3 天更新一次足够 Meta 核心不需要 type 和 path 参数
rule-info: &rule-info
  type: http
  interval: 259200

# domain or ipcidr 推荐使用 匹配更高效
domain: &rule-domain
  behavior: domain
  <<: *rule-info

# 引用规则集
rule-providers:
  Apple:
    <<: *rule-domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt
    path: ./Providers/Ruleset/Apple.yaml
  Google:
    <<: *rule-domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt
    path: ./Providers/Ruleset/Google.yaml  
  iCloud:
    <<: *rule-domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt
    path: ./Providers/Ruleset/iCloud.yaml
  Private:
    <<: *rule-domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
    path: ./Providers/Ruleset/Private.yaml
  Proxy:
    <<: *rule-domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    path: ./Providers/Ruleset/Proxy.yaml
  GFWList:
    <<: *rule-domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
    path: ./Providers/Ruleset/GFWList.yaml
  BiliBili:
    <<: *rule-domain
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/BiliBili/BiliBili.yaml
    path: ./Providers/Ruleset/BiliBili.yaml
  GlobalMedia:
    <<: *rule-domain
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GlobalMedia/GlobalMedia.yaml
    path: ./Providers/Ruleset/GlobalMedia.yaml
  # Ad: # anti-AD的广告过滤 按需启用
  #   <<: *rule-domain
  #   url: https://anti-ad.net/clash.yaml
  #   path: ./Providers/Ruleset/anti-ad-clash.yaml

# 自定义规则
rules:
  - GEOIP,LAN,DIRECT # LAN 使用直连
  - GEOIP,CN,DIRECT # CN 使用直连
  - RULE-SET,Apple,🍎 苹果服务
  - RULE-SET,Google,☁️ 谷歌服务
  - RULE-SET,iCloud,🍎 苹果服务
  - RULE-SET,BiliBili,📺 哔哩哔哩
  - RULE-SET,GlobalMedia,🌍 国外媒体
  - RULE-SET,Proxy,🚀 手动切换
  - RULE-SET,Private,DIRECT
  # - RULE-SET,Ad,🆎 AdBlock # 广告过滤 按需启用
  # ========其他自定义规则示例========
  - DOMAIN-SUFFIX,ai.com,🤖 OpenAi # 域名后缀匹配 使用代理组
  - DOMAIN-SUFFIX,openai.com,🤖 OpenAi
  - DOMAIN-SUFFIX,identrust.com,🤖 OpenAi
  - IP-CIDR,162.159.193.0/24,DIRECT # IP 段匹配 Cloudflare
  - IP-CIDR,91.108.0.0/16,🚀 手动切换,no-resolve
  - IP-CIDR,109.239.140.0/24,🚀 手动切换,no-resolve
  - DOMAIN-KEYWORD,-cn,DIRECT
  - DOMAIN-SUFFIX,local,DIRECT
  - DOMAIN-SUFFIX,cn,DIRECT
  - DOMAIN-SUFFIX,umeng.co,REJECT # REJECT 广告拦截
  - DOMAIN-SUFFIX,umeng.com,REJECT
  - DOMAIN-SUFFIX,umtrack.com,REJECT
  - DOMAIN-SUFFIX,ad.xiaomi.com,REJECT
  - DOMAIN-SUFFIX,ad1.xiaomi.com,REJECT

  # 上面规则都未命中
  - MATCH,🐟 漏网之鱼 # 使用漏网之鱼分组 可以理解为黑名单模式
  # - MATCH, DIRECT # 使用直连 即白名单模式 配合下方GFWList效果更佳
  # - RULE-SET,GFWList,🚀 手动切换
