port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
tcp-concurrent: true
external-controller: :9090
external-ui: ./ui
geodata-mode: true
global-client-fingerprint: chrome
profile:
  store-selected: true
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  force-domain:
    - "+.netflix.com"
    - "+.nflxvideo.net"
    - "+.amazonaws.com"
    - "+.media.dssott.com"
  skip-domain:
    - "+.apple.com"
    - Mijia Cloud
    - dlg.io.mi.com
  sniff:
    TLS:
    HTTP:
      ports:
        - 80
        - 8080-8880
      override-destination: true
tun:
  enable: false
  stack: mixed
  dns-hijack:
    - "any:53"
  auto-route: true
  auto-detect-interface: true

dns:
  enable: false
  listen: :1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
    - "[2402:4e00::]"
    - "[2400:3200::1]"
  nameserver:
    - "tls://8.8.4.4#dns"
    - "tls://1.0.0.1#dns"
    - "tls://[2001:4860:4860::8844]#dns"
    - "tls://[2606:4700:4700::1001]#dns"
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  nameserver-policy:
    "geosite:cn,private":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query

experimental:
  ignore-resolve-fail: true
unified-delay: true

# proxy-providers参数锚点 方便多订阅源复用
pvd-info: &pvd-info # 更新订阅周期 3天
  interval: 259200
  # 节点状态检查
  health-check:
    enable: true
    url: http://www.gstatic.com/generate_204
    interval: 600

# clash 链接无须转换 节点订阅转换 https://sub.xeton.dev/sub?target=clash&url=订阅链接多个用|分割&list=true&udp=false
# 可选自建或其他订阅转换工具 推荐选择输出为 NodeList 也可处理节点过滤
proxy-providers:
  Subscribe:
    # 代理提供商类型 http|file
    type: http
    # 引用参数锚点
    <<: *pvd-info
    # 排除关键字使用exclude参数(UrlCode编码)例如要排除"海外|到期"在链接后追加 &exclude=%E6%B5%B7%E5%A4%96%7C%E5%88%B0%E6%9C%9F
    url: "https://dy.byxiao.top/v2ray&list=true&udp=true&exclude=%E6%B5%B7%E5%A4%96%7C%E5%88%B0%E6%9C%9F"
    # 订阅内容保存路径
    path: ./Providers/Proxies/Subscribe.yaml
    # filter: 'HK|TW|US' # 过滤节点 Golang regex不支持复杂表达式 建议用订阅转换工具过滤
  # ======== 引用当前已有clash配置文件示例 ========
  # MyConfig:
  #   type: file
  #   path: MyConfig.yaml # 当前已有配置文件path
  #   health-check:
  #     enable: true
  #     interval: 36000
  #     url: http://www.gstatic.com/generate_204
  #   filter: 'HK|JP|VN|SG'

  # 定义节点过滤参数锚点
  filter-info: &filter-info
    type: file
    path: ./Providers/Proxies/Subscribe.yaml

  # 代理组中不支持 filter 在这处理
  🔞 自建节点: { <<: *filter-info, filter: "sing-box|Oracle|Raksmart|hy2" }  
  💦 BPB: { <<: *filter-info, filter: "BPB|💦" }
  🇭🇰 香港节点: { <<: *filter-info, filter: "🇭🇰|港|HK|hk|Hong Kong|HongKong|hongkong|HKG" }
  🇹🇼 台湾节点: { <<: *filter-info, filter: "🇹🇼|台湾|台北|TW|🇹🇼|Taiwan" }
  🇯🇵 日本节点: { <<: *filter-info, filter: "🇯🇵|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan" }
  🇸🇬 新加坡节点: { <<: *filter-info, filter: "新加坡|🇸🇬|SG|Singapore" }
  🇺🇲 美国节点: { <<: *filter-info, filter: "美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|ATL|BUF|DFW|EWR|IAD|LAX|MCI|MIA|ORD|PHX|PDX|SEA|SJC" }
  🇰🇷 韩国节点: { <<: *filter-info, filter: "韩国|韩|KR|🇰🇷|Korea" }

# 使用proxy-providers中的节点 定义锚点
all-proxy: &all-proxy
  type: select
  use:
    - Subscribe # 引用订阅文件
    # - MyConfig # 引用已有配置文件

# 其他代理 自建等写在这里
proxies:
  - { name: "ss1", type: ss, server: server, port: 443, cipher: chacha20-ietf-poly1305, password: "password", udp: true}
  # - { name: "ss2", type: ss, server: server, port: 443, cipher: chacha20-ietf-poly1305, password: "password", udp: true}
# 定义自建代理锚点
local-proxy: &local-proxy
  - ss1
  # - ss2

# 定义自动测速节点
auto: &auto-select
  type: url-test
  lazy: true
  url: http://www.gstatic.com/generate_204
  # 节点检测 间隔10分钟
  interval: 600
  use:
    - Subscribe
    # - MyConfig # 引用已有配置文件

# 定义分流参数锚点
group-proxy: &group-proxy
  type: select
  proxies: [🚀 手动切换, ♻️ 自动选择,🇭🇰 香港节点, 🇸🇬 新加坡节点, 🇺🇲 美国节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 💦 BPB, 🔞 自建节点, DIRECT]

# 定义代理分组 与锚点合并
proxy-groups:
  - name: 🚀 手动切换
    <<: *all-proxy
    proxies:
      - ♻️ 自动选择
      # - 🔧 自定节点 # 按需是否使用自定义节点
  - name: ♻️ 自动选择
    <<: *auto-select
    proxies:
      # 添加自定义节点
      # - ss1
      # - ss2
  - name: 🌍 国外媒体
    type: select
    <<: *group-proxy
    proxies: [🚀 手动切换, 🇸🇬 新加坡节点, 🇺🇲 美国节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 💦 BPB, 🔞 自建节点, DIRECT]
  - name: 🍎 苹果服务
    <<: *group-proxy
  - name: 📺 哔哩哔哩
    type: select
    proxies: [DIRECT, 🇭🇰 香港节点, 🇹🇼 台湾节点]
  - name: 🤖 OpenAi
    type: select
    proxies: [🚀 手动切换, 🇺🇲 美国节点, 🇯🇵 日本节点, 🔞 自建节点]
  # - name: 🆎 AdBlock # 广告过滤分组 已用其他过滤工具不建议Clash中再启用
  #   type: select
  #   proxies: [REJECT, DIRECT]

  # 代理转发链 relay 示例 新版本推荐使用更快速的 tunnels 模式
  # proxies 中不应该包含 relay 节点 不支持 UDP
  # 流量示意 clash <-> vmess <-> ss1 <-> 互联网 (这样是为了用自建节点落地解决机场跳 IP 问题)
  # - name: 🔁 relay
  #   type: relay
  #   proxies: # !!!注意proxies中不能有relay节点
  #     - vmess
  #     - ss1
  - name: 🔧 自定节点
    type: select
    proxies: *local-proxy

  - name: 🐟 漏网之鱼
    <<: *group-proxy

  # Meta 核心节点按地区分组示例 (Clash Premium 不支持此种过滤)
  # - name: 🇭🇰 香港节点
  #   <<: *all-proxy
  #   filter: '港|HK|(?i)Hong'
  # - name: 🇨🇳 台湾节点
  #   <<: *all-proxy
  #   filter: '台|湾|TW|(?i)Taiwan'

  # 节点按地区分组 当前手动选择节点 可参考auto-select锚点改为自动选择
  - name: 🇭🇰 香港节点
    type: auto-select
    use:
      - 🇭🇰 香港节点
  - name: 🇹🇼 台湾节点
    type: auto-select
    use:
      - 🇹🇼 台湾节点
  - name: 🇯🇵 日本节点
    type: auto-select
    use:
      - 🇯🇵 日本节点
  - name: 🇸🇬 新加坡节点
    type: auto-select
    use:
      - 🇸🇬 新加坡节点
  - name: 🇺🇲 美国节点
    type: auto-select
    use:
      - 🇺🇲 美国节点
  - name: 🇰🇷 韩国节点
    type: auto-select
    use:
      - 🇰🇷 韩国节点

# 定义规则集参数锚点 interval 3 天更新一次足够 Meta 核心不需要 type 和 path 参数
rule-info: &rule-info
  type: http
  interval: 259200

# classical 不推荐使用 复杂度较高不建议添加太多
#classical: &rule-classical
  #behavior: classical
  #<<: *rule-info
# domain or ipcidr 推荐使用 匹配更高效
domain: &rule-domain
  behavior: domain
  <<: *rule-info

# 引用规则集
rule-providers:
  Apple:
    <<: *rule-domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt
    path: ./Providers/Ruleset/Apple.yaml
  iCloud:
    <<: *rule-domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt
    path: ./Providers/Ruleset/iCloud.yaml
  Private:
    <<: *rule-domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
    path: ./Providers/Ruleset/Private.yaml
  Proxy:
    <<: *rule-domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    path: ./Providers/Ruleset/Proxy.yaml
  GFWList:
    <<: *rule-domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
    path: ./Providers/Ruleset/GFWList.yaml
  BiliBili:
    <<: *rule-classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/BiliBili/BiliBili.yaml
    path: ./Providers/Ruleset/BiliBili.yaml
  GlobalMedia:
    <<: *rule-classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GlobalMedia/GlobalMedia.yaml
    path: ./Providers/Ruleset/GlobalMedia.yaml
  # Ad: # anti-AD的广告过滤 按需启用
  #   <<: *rule-domain
  #   url: https://anti-ad.net/clash.yaml
  #   path: ./Providers/Ruleset/anti-ad-clash.yaml

# 自定义规则
rules:
  - GEOIP,LAN,DIRECT # LAN 使用直连
  - GEOIP,CN,DIRECT # CN 使用直连
  - RULE-SET,Apple,🍎 苹果服务
  - RULE-SET,iCloud,🍎 苹果服务
  - RULE-SET,BiliBili,📺 哔哩哔哩
  - RULE-SET,GlobalMedia,🌍 国外媒体
  - RULE-SET,Proxy,🚀 手动切换
  - RULE-SET,Private,DIRECT
  # - RULE-SET,Ad,🆎 AdBlock # 广告过滤 按需启用
  # ========其他自定义规则示例========
  - DOMAIN-SUFFIX,ai.com,🤖 OpenAi # 域名后缀匹配 使用代理组
  - DOMAIN-SUFFIX,openai.com,🤖 OpenAi
  - DOMAIN-SUFFIX,identrust.com,🤖 OpenAi
  - IP-CIDR,162.159.193.0/24,DIRECT # IP 段匹配 Cloudflare
  - IP-CIDR,91.108.0.0/16,🚀 手动切换,no-resolve
  - IP-CIDR,109.239.140.0/24,🚀 手动切换,no-resolve
  - DOMAIN-KEYWORD,-cn,DIRECT
  - DOMAIN-SUFFIX,local,DIRECT
  - DOMAIN-SUFFIX,cn,DIRECT
  - DOMAIN-SUFFIX,umeng.co,REJECT # REJECT 广告拦截
  - DOMAIN-SUFFIX,umeng.com,REJECT
  - DOMAIN-SUFFIX,umtrack.com,REJECT
  - DOMAIN-SUFFIX,ad.xiaomi.com,REJECT
  - DOMAIN-SUFFIX,ad1.xiaomi.com,REJECT

  # 上面规则都未命中
  - MATCH,🐟 漏网之鱼 # 使用漏网之鱼分组 可以理解为黑名单模式
  # - MATCH, DIRECT # 使用直连 即白名单模式 配合下方GFWList效果更佳
  # - RULE-SET,GFWList,🚀 手动切换
